version: 2.1
parameters:
  version:
    type: string
    default: "latest"
orbs:
  gh: circleci/github-cli@1.0.4
  docker: circleci/docker@1.7.0

jobs:
  build-job:
    docker:
      - image: pvmm/msx-forth83:golang
    environment:
      VERSION: << pipeline.parameters.version >>
    working_directory: /root/forth83
    steps:
      - checkout
      - run: make
      - run: cd /root && ./docker-entrypoint.sh openmsx -script /root/forth83/compile.tcl
      - run: mv /root/forth.dsk /root/msx-forth83-latest.dsk
      - run: echo "export PATH=/root/go/bin:$PATH" >> $BASH_ENV
     
  
  # deploy-job:
  #   docker: 
  #     - image: cimg/base:2021.04
  #   steps:
  #     - gh/release:
  #         draft: false 
  #         files: /root/msx-forth83-latest.dsk 
  #         prerelease: true 
  #         tag: latest 
  #         title: Latest release 
  #         version: latest 
  #         token: GITHUB_TOKEN

workflows:
  build-deploy-workflow:
    jobs:
      - build-job
      - gh/release:
          draft: false 
          files: /root/msx-forth83-latest.dsk 
          prerelease: true 
          tag: latest 
          title: Latest release
          version: latest 
          token: GITHUB_TOKEN
          requires: 
            - build-job