version: 2.1
parameters:
  version:
    type: string
    default: "latest"
orbs:
  github-release: h-matsuo/github-release@0.1.3
jobs:
  build:
    docker:
      - image: pvmm/msx-forth83:golang
    environment:
      VERSION: << pipeline.parameters.version >>
    working_directory: /root/forth83
    steps:
      - checkout
      - run: make
      - run: cd /root && ./docker-entrypoint.sh openmsx -script /root/forth83/compile.tcl
      - run: mv /root/forth.dsk /root/msx-forth83-${VERSION}.dsk
      - run: echo "export PATH=/root/go/bin:$PATH" >> $BASH_ENV
      - run: echo ${CIRCLE_PROJECT_NAME}, ${CIRCLE_PROJECT_REPONAME}, ${CIRCLE_SHA1}, ${VERSION}
      - github-release/create:
          tag: ${VERSION}
          title: Version ${VERSION}
          description: This release is version ${VERSION}.
          file-path: /root/msx-forth83-${VERSION}.dsk
