version: 2.1
parameters:
  version:
    type: string
    default: "latest"
orbs:
  github-cli: circleci/github-cli@1.0.4
  docker: circleci/docker@1.7.0
  github-release: h-matsuo/github-release@0.1.3

jobs:
  build-job:
    docker:
      - image: pvmm/msx-forth83:golang
    environment:
      VERSION: << pipeline.parameters.version >>
    working_directory: /root/forth83
    steps:
      - checkout
      - run: make
      - run: cd /root && ./docker-entrypoint.sh openmsx -script /root/forth83/compile.tcl
      - run: mv /root/forth.dsk /root/msx-forth83-latest.dsk
      - run: cp /root/msx-forth83-latest.dsk /tmp/msx-forth83-latest.dsk
      - run: echo "export PATH=/root/go/bin:$PATH" >> $BASH_ENV
      - store_artifacts:
          path: /root/msx-forth83-latest.dsk
      - persist_to_workspace:
          root: /tmp
          paths:
            - msx-forth83-latest.dsk
  # deploy-job:
  #   docker: 
  #     - image: cimg/base:2021.04
  #   steps:
  #     - run: sudo apt-get update
  #     - github-cli/release:
  #         draft: false 
  #         files: /root/msx-forth83-latest.dsk 
  #         prerelease: true 
  #         tag: latest 
  #         title: Latest release 
  #         version: latest 
  #         token: GITHUB_TOKEN

workflows:
  build-deploy-workflow:
    jobs:
      - build-job
      - github-cli/release:
          draft: false
          files: msx-forth83-latest.dsk 
          prerelease: true
          tag: latest
          title: Latest build
          requires: 
            - build-job

      # - deploy-job:
      #     requires: 
      #       - build-job